# Generated by Django 5.2.9 on 2026-02-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_movie_backdrop_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='streaming_providers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
