# Generated by Django 5.2.9 on 2026-02-04 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_movie_streaming_providers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='streaming_providers',
        ),
    ]
