# Generated by Django 5.2.9 on 2026-02-05 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_movie_streaming_providers'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieExposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exposed_count', models.PositiveIntegerField(default=0)),
                ('last_exposed_at', models.DateTimeField(blank=True, null=True)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exposure', to='core.movie')),
            ],
        ),
        migrations.CreateModel(
            name='SessionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_swipes', models.PositiveIntegerField(default=0)),
                ('total_matches', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('ended_by', models.CharField(blank=True, choices=[('user', 'User'), ('no_more_movies', 'No More Movies'), ('disconnect', 'Disconnect')], max_length=20, null=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='core.session')),
            ],
        ),
    ]
