# Generated by Django 5.2.9 on 2026-02-05 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_movieexposure_sessionstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieexposure',
            name='exposed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movieexposure',
            name='movie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.movie'),
        ),
    ]
