# Generated by Django 5.2.9 on 2026-02-05 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_usertastesignal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionChemistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=64)),
                ('match_count', models.PositiveIntegerField(default=0)),
                ('swipe_count', models.PositiveIntegerField(default=0)),
                ('last_matched_at', models.DateTimeField(blank=True, null=True)),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemistry_as_a', to=settings.AUTH_USER_MODEL)),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemistry_as_b', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_a', 'user_b', 'tag')},
            },
        ),
    ]
