# Generated by Django 5.2.9 on 2026-02-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sessionchemistry'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionstats',
            name='highlights',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sessionstats',
            name='quality_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
