# Generated by Django 5.2.9 on 2026-02-05 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sessionstats_highlights_sessionstats_quality_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieTagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0)),
                ('from_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='core.movietag')),
                ('to_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='core.movietag')),
            ],
            options={
                'unique_together': {('from_tag', 'to_tag')},
            },
        ),
    ]
