# Generated by Django 5.2.9 on 2026-02-06 10:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_session_industry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='industry',
        ),
        migrations.AddField(
            model_name='genre',
            name='industry',
            field=models.CharField(choices=[('bollywood', 'Bollywood'), ('hollywood', 'Hollywood')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
