# Generated by Django 5.2.9 on 2026-02-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_movie_poster_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='original_language',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
