# Generated by Django 5.2.9 on 2026-02-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_movie_original_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='industry',
            field=models.CharField(choices=[('bollywood', 'Indian Movies'), ('hollywood', 'Hollywood')], max_length=50),
        ),
    ]
