# Generated by Django 5.2.9 on 2026-02-06 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_genre_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='core.genre'),
        ),
    ]
