# Generated by Django 5.2.9 on 2026-02-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_session_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='industry',
            field=models.CharField(blank=True, choices=[('bollywood', 'Indian Movies'), ('hollywood', 'Hollywood')], max_length=20, null=True),
        ),
    ]
