# Generated by Django 5.2.9 on 2026-02-08 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_session_industry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='industry',
        ),
    ]
