# Generated by Django 5.2.9 on 2026-02-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_session_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='industry',
            field=models.CharField(blank=True, choices=[('bollywood', 'Bollywood'), ('hollywood', 'Hollywood')], max_length=20, null=True),
        ),
    ]
