# Generated by Django 5.2.9 on 2026-02-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_session_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='guest_preferences',
            field=models.JSONField(blank=True, help_text="Guest's mood/vibe preferences", null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='host_preferences',
            field=models.JSONField(blank=True, help_text="Host's mood/vibe preferences", null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='preferences_set',
            field=models.BooleanField(default=False, help_text='Whether both users completed the questionnaire'),
        ),
    ]
