# Generated by Django 5.2.9 on 2026-02-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_session_guest_preferences_session_host_preferences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='selected_languages',
            field=models.JSONField(blank=True, help_text="User-selected languages like ['hi', 'gu', 'mr']", null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='industry',
            field=models.CharField(blank=True, choices=[('bollywood', 'Bollywood'), ('hollywood', 'Hollywood'), ('mixed', 'Mixed')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='industry',
            field=models.CharField(blank=True, choices=[('bollywood', 'Bollywood'), ('hollywood', 'Hollywood'), ('mixed', 'Mixed')], max_length=50, null=True),
        ),
    ]
