# Generated by Django 5.2.9 on 2026-02-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_session_selected_languages_alter_genre_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='streaming_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
