# Generated by Django 5.2.9 on 2026-02-13 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_movie_streaming_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('country_code', models.CharField(default='IN', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieStreamingAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True)),
                ('monetization_type', models.CharField(choices=[('flatrate', 'Subscription'), ('buy', 'Buy'), ('rent', 'Rent')], max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.movie')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.streamingprovider')),
            ],
            options={
                'unique_together': {('movie', 'provider')},
            },
        ),
    ]
