# Generated by Django 5.2.9 on 2026-02-13 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_streamingprovider_moviestreamingavailability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='streaming_url',
        ),
    ]
